# Generated by Django 2.1.5 on 2023-01-27 23:09

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False #添加atomic，尝试修改表的名字（成功了！！！）
    dependencies = [
        ('rango', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Catagory',
            new_name='Category',
        ),
    ]
